#!/bin/sh
########################################
#                                      #
# GE job script for ECDF Cluster       #
#                                      #
# by Amir H. Farmahini                 #
#                                      #
#                                      #
########################################
 
# Grid Engine options
 
#$ -N KH_new2
#$ -cwd
#$ -l h_rt=600:00:00
#$ -l h_vmem=16G
#$ -pe sharedmem 1
# Initialise environment module
 . /etc/profile.d/modules.sh

# To prevent segmentation fault 
ulimit -s unlimited 

#use module 
module load intel/2016

#run program
/exports/csce/eddie/eng/groups/eddie_see_imp_bio/Amir/KH/kh_perc_d_fast_for_michael/kh.exe < input.dat > results.dat




